project:
  type: website
  preview:
    port: 3000
    browser: false

website:
  title: "Erik Gaasedelen"
  site-url: https://rachel.fast.ai
  description: "AI, cardiac science, & learnings"
  image: "/images/thomas-card.jpg"
  open-graph:
    description: "AI, cardiac science, & learnings"
  twitter-card:
    creator: "@erikgaas"
    site: "@erikgaas"
    description: "AI, cardiac science, & learnings"
  # margin-header: subscribe.html
  # body-footer: "<br><br><i>I look forward to reading your responses. Create a free GitHub account to comment below.</i>"
  # comments:
  #   giscus:
  #       repo: racheltho/rachel-blog
  #       repo-id: "R_kgDOIxf7pQ"
  #       category: "Announcements"
  #       category-id: "DIC_kwDOIxf7pc4CcEZ1"
  #       mapping: "pathname"
  #       reactions-enabled: true
  #       input-position: "bottom"
  #       theme: "light"
       
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: twitter
        href: https://twitter.com/erikgaas
      - icon: linkedin
        href: https://www.linkedin.com/in/erikgaas
      # - icon: youtube
      #   href: https://www.youtube.com/playlist?list=PLtmWHNX-gukLQlMvtRJ19s7-8MrnRV6h6
      - icon: rss
        href: index.xml
      - text: Archive
        href: archive.qmd  
format:
  html:
    theme: flatly
    linkcolor: "#168873"
    css: styles.css



